[[languages]]
name = "rust"
auto-format = true

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
inlayHints.bindingModelHints.enable = true

[language-server.rust-analyzer.config.check]
command = "clippy"

[[languages]]
name = "cpp"
roots = ["CMakeLists.txt"]
indent = {tab-width=2}

[language-server.clangd]
command = "clangd"
